export const SAVE_ORIGIN = 'SAVE_ORIGIN';
export const SAVE_DESTINATION = 'SAVE_DESTINATION';
export const SAVE_PARCEL = 'SAVE_PARCEL';
export const SET_PARCELS = 'SET_PARCELS';
export const SET_CENTER = 'SET_CENTER';
export const SET_POLYLINE_ROUTES = 'SET_POLYLINE_ROUTES';
export const SET_PRICING_VALUES  = 'SET_PRICING_VALUES';
export const SAVE_TRANSPORT_TYPE  = 'SAVE_TRANSPORT_TYPE';